# example toml
[experiment]
name = "Transformer with attention distance"
description = "Evaluating a model with attention distance mask"

[data]
data_dir = "/data/atlas/users/spshenov/ml_input_data"
# trackml_tiny_10to50tracks_100events.csv
# trackml_short_10to50_tracks_5k_events.csv
# trackml_10to50tracks_40kevents.csv
# trackml_200to500tracks_40kevents.csv
data_file = "trackml_10to50tracks_40kevents.csv"
dataloader_num_workers = 4
num_classes = 451


[model]
# checkpoint_path = "/data/atlas/users/spshenov/trained_models/models_5_features_600epochs/model_trackml_10to50_best.pth"
checkpoint_path = "/data/atlas/users/spshenov/trained_models/20241104_120903_orthodox-elegant-bloodhound_train/model_best.pth"
num_encoder_layers = 6
d_model = 32
n_head = 4
input_size = 3
output_size = 5
dim_feedforward = 128
dropout = 0.1
use_flash_attention = false
use_att_mask = false


[training]
batch_size = 64


[output]
base_path = "/data/atlas/users/spshenov/evaluation"

[logging]
level = "INFO"

[wandb]
entity = "spshenov-university-of-amsterdam"
project_name = "transformer_for_particle_tracking"

[bin_ranges.q]
min = -1.5
max = 1.5
step = 1

[bin_ranges.pt]
min = 0
max = 5
step = 0.5

[bin_ranges.eta]
min = 0
max = 4
step = 0.5

[bin_ranges.sin_phi]
min = -1
max = 1
step = 0.2