# example toml
[experiment]
name = "Transformer with attention distance"
description = "Evaluating a model with attention distance mask"

[data]
data_dir = "/data/atlas/users/spshenov/ml_input_data"
data_file = "trackml_tiny_10to50tracks_100events.csv"
dataloader_num_workers = 4
num_classes = 451


[model]
checkpoint_path = "/data/atlas/users/spshenov/trained_models/20241022_141723_meteoric-capable-orangutan/model_best.pth"
num_encoder_layers = 6
d_model = 32
n_head = 4
input_size = 3
output_size = 5
dim_feedforward = 128
dropout = 0.1
use_flash_attention = false


[training]
batch_size = 64


[output]
base_path = "/data/atlas/users/spshenov/studio/evaluation"

[logging]
level = "INFO"

[wandb]
entity = "spshenov-university-of-amsterdam"
project_name = "transformer_for_particle_tracking"

[sweep]
method = "random"  # or 'grid', 'bayes'
metric_name = "test/event score"
metric_goal = "maximize"  # or 'minimize'

[sweep.parameters]
min_cl_size = {values = [5]}
min_samples = {values = [3, 4]}