# example toml
[experiment]
name = "Transformer with attention distance"
description = "Evaluating a model with attention distance mask"

[data]
data_dir = "/data/atlas/users/spshenov/ml_input_data"
# trackml_tiny_10to50tracks_100events.csv
# trackml_short_10to50_tracks_5k_events.csv
# trackml_10to50tracks_40kevents.csv
data_file = "trackml_tiny_10to50tracks_100events.csv"


[model]
# checkpoint_path = "/data/atlas/users/spshenov/studio/trained_models/20241028_194927_great-spoonbill-of-refinement_train/model_best.pth"
checkpoint_path = "/data/atlas/users/spshenov/trained_models/models_5_features_600epochs/model_trackml_10to50_best.pth"
num_encoder_layers = 6
d_model = 32
n_head = 4
input_size = 3
output_size = 5
dim_feedforward = 128
dropout = 0.1
use_flash_attention = false
use_att_mask = false


[training]
batch_size = 64


[output]
base_path = "/data/atlas/users/spshenov/studio/evaluation"

[logging]
level = "INFO"

[wandb]
entity = "spshenov-university-of-amsterdam"
project_name = "transformer_for_particle_tracking"

[sweep]
method = "random"  # or 'grid', 'bayes'
metric_name = "test/event score"
metric_goal = "maximize"  # or 'minimize'

[sweep.parameters]
min_cl_size = {values = [5]}
min_samples = {values = [3, 4]}

[bin_ranges.q]
min = -1.5
max = 1.5
step = 1

[bin_ranges.log_p]
min = -3
max = 5
step = 0.5

[bin_ranges.theta]
min = 0
max = 3.141592
step = 0.314

[bin_ranges.sin_phi]
min = -1
max = 1
step = 0.2
